-- VHDL Entity RISCV_Processor_lib.address_gen.interface
--
-- Created:
--          by - st161569.st161569 (pc029)
--          at - 14:49:24 05/14/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

ENTITY address_gen IS
   PORT( 
      address : OUT    std_logic_vector (7 DOWNTO 0)
   );

-- Declarations

END address_gen ;

