-- VHDL Entity RISCV_Processor_lib.io_ram_mux.interface
--
-- Created:
--          by - st161569.st161569 (pc043)
--          at - 18:06:04 07/10/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;
LIBRARY RISCV_Processor_lib;
USE RISCV_Processor_lib.types.ALL;
USE RISCV_Processor_lib.isa_defines.ALL;
LIBRARY altera_mf;
USE altera_mf.altera_mf_components.all;

ENTITY io_ram_mux IS
   PORT( 
      io_rdata           : IN     word_t;
      is_io_access       : IN     boolean;
      ram_result         : IN     word_t;
      data_memory_result : OUT    word_t
   );

-- Declarations

END io_ram_mux ;

