-- VHDL Entity RISCV_Processor_lib.pc_mux.interface
--
-- Created:
--          by - st161569.st161569 (pc043)
--          at - 15:40:06 07/09/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;
LIBRARY RISCV_Processor_lib;
USE RISCV_Processor_lib.types.ALL;
USE RISCV_Processor_lib.isa_defines.ALL;
LIBRARY altera_mf;
USE altera_mf.altera_mf_components.all;

ENTITY pc_mux IS
   PORT( 
      dbta                       : IN     word_t;
      dbta_valid_ex              : IN     boolean;
      imm_or_bta_dc              : IN     word_t;
      jump_predicted_if          : IN     boolean;
      pc_pf                      : IN     word_t;
      predicted_target_addr_if   : IN     word_t;
      return_addr                : IN     word_t;
      sbta_valid_dc              : IN     boolean;
      wrong_jump_prediction_dbpu : IN     boolean;
      wrong_jump_prediction_sbpu : IN     boolean;
      pc                         : OUT    word_t
   );

-- Declarations

END pc_mux ;

