-- VHDL Entity RISCV_Processor_lib.sbpu.interface
--
-- Created:
--          by - st161569.st161569 (pc043)
--          at - 16:45:10 07/09/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;
LIBRARY RISCV_Processor_lib;
USE RISCV_Processor_lib.types.ALL;
USE RISCV_Processor_lib.isa_defines.ALL;
LIBRARY altera_mf;
USE altera_mf.altera_mf_components.all;

ENTITY sbpu IS
   PORT( 
      imm_or_bta_dc              : IN     word_t;
      jump_predicted_dc          : IN     boolean;
      pc_dc                      : IN     word_t;
      sbpu_mode_dc               : IN     sbpu_mode_t;
      btc_controls_sbpu          : OUT    btc_controls_t;
      wrong_jump_prediction_sbpu : OUT    boolean
   );

-- Declarations

END sbpu ;

