-- VHDL Entity RISCV_Processor_lib.bpb.interface
--
-- Created:
--          by - st161569.st161569 (pc028)
--          at - 16:40:04 06/25/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;
LIBRARY RISCV_Processor_lib;
USE RISCV_Processor_lib.types.ALL;
USE RISCV_Processor_lib.isa_defines.ALL;
LIBRARY altera_mf;
USE altera_mf.altera_mf_components.all;

ENTITY bpb IS
   PORT( 
      clk                      : IN     std_logic;
      dbta_valid_ex            : IN     boolean;
      jump_predicted_ex        : IN     boolean;
      jump_relevant_for_bpb_dc : IN     boolean;
      jump_relevant_for_bpb_ex : IN     boolean;
      pc_dc                    : IN     word_t;
      pc_ex                    : IN     word_t;
      res_n                    : IN     std_logic;
      jump_predicted_dc        : OUT    boolean;
      wrong_jump_prediction    : OUT    boolean
   );

-- Declarations

END bpb ;

