-- VHDL Entity RISCV_Processor_lib.bpu.interface
--
-- Created:
--          by - st161569.st161569 (pc043)
--          at - 16:44:26 07/09/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;
LIBRARY RISCV_Processor_lib;
USE RISCV_Processor_lib.types.ALL;
USE RISCV_Processor_lib.isa_defines.ALL;
LIBRARY altera_mf;
USE altera_mf.altera_mf_components.all;

ENTITY bpu IS
   PORT( 
      bpb_controls               : IN     bpb_controls_t;
      btc_controls_dbpu          : IN     btc_controls_t;
      btc_controls_sbpu          : IN     btc_controls_t;
      clk                        : IN     std_logic;
      pc                         : IN     word_t;
      res_n                      : IN     std_logic;
      wrong_jump_prediction_dbpu : IN     boolean;
      wrong_jump_prediction_sbpu : IN     boolean;
      bpb_state_if               : OUT    std_logic_vector (1 DOWNTO 0);
      jump_predicted_if          : OUT    boolean;
      predicted_target_addr_if   : OUT    word_t
   );

-- Declarations

END bpu ;

