-- VHDL Entity RISCV_Processor_lib.bta_adder.interface
--
-- Created:
--          by - st161569.st161569 (pc043)
--          at - 17:25:58 05/29/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;
LIBRARY RISCV_Processor_lib;
USE RISCV_Processor_lib.types.ALL;

ENTITY bta_adder IS
   PORT( 
      imm_dc : IN     word_t;
      pc_dc  : IN     word_t;
      bta    : OUT    word_t
   );

-- Declarations

END bta_adder ;

