-- VHDL Entity UPN_Rechner_Lib.button.interface
--
-- Created:
--          by - st161569.st161569 (pc043)
--          at - 17:18:09 04/24/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

ENTITY button IS
   PORT( 
      clk   : IN     std_logic;
      res_n : IN     std_logic;
      tx_n  : IN     std_logic;
      key   : OUT    std_logic
   );

-- Declarations

END button ;

