-- VHDL Entity RISCV_Processor_lib.clk_res_gen.interface
--
-- Created:
--          by - st161569.st161569 (pc029)
--          at - 14:49:24 05/14/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

ENTITY clk_res_gen IS
   PORT( 
      clk   : OUT    std_logic;
      res_n : OUT    std_logic
   );

-- Declarations

END clk_res_gen ;

