-- VHDL Entity RISCV_Processor_lib.convert_to_big_endian.interface
--
-- Created:
--          by - st161569.st161569 (pc043)
--          at - 16:23:10 07/11/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;
LIBRARY RISCV_Processor_lib;
USE RISCV_Processor_lib.types.ALL;
USE RISCV_Processor_lib.isa_defines.ALL;
LIBRARY altera_mf;
USE altera_mf.altera_mf_components.all;

ENTITY convert_to_big_endian IS
   PORT( 
      instruction_word_rom        : IN     word_t;
      instruction_word_big_endian : OUT    word_t
   );

-- Declarations

END convert_to_big_endian ;

