-- VHDL Entity RISCV_Processor_lib.cpu.interface
--
-- Created:
--          by - st161569.st161569 (pc029)
--          at - 16:10:28 05/14/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

ENTITY cpu IS
   PORT( 
      clk   : IN     std_logic;
      res_n : IN     std_logic
   );

-- Declarations

END cpu ;

