-- VHDL Entity RISCV_Processor_lib.data_memory.interface
--
-- Created:
--          by - st161569.st161569 (pc029)
--          at - 16:53:46 05/21/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;
LIBRARY RISCV_Processor_lib;
USE RISCV_Processor_lib.types.ALL;

ENTITY data_memory IS
   PORT( 
      alu_result_mem     : IN     word_t;
      clk                : IN     std_logic;
      mem_mode_mem       : IN     mem_mode_t;
      res_n              : IN     std_logic;
      store_data         : IN     word_t;
      data_memory_result : OUT    word_t
   );

-- Declarations

END data_memory ;

