-- VHDL Entity RISCV_Processor_lib.dbpu.interface
--
-- Created:
--          by - st161569.st161569 (pc043)
--          at - 15:56:39 06/05/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;
LIBRARY RISCV_Processor_lib;
USE RISCV_Processor_lib.types.ALL;

ENTITY dbpu IS
   PORT( 
      alu_flags      : IN     flag_t;
      alu_result_ex  : IN     word_t;
      dbpu_mode_ex   : IN     dbpu_mode_t;
      imm_or_bta_ex  : IN     word_t;
      dbta           : OUT    word_t;
      dbta_valid_ex  : OUT    boolean;
      is_return_addr : OUT    boolean
   );

-- Declarations

END dbpu ;

