-- VHDL Entity RISCV_Processor_lib.dc_ex_pipeline_reg.interface
--
-- Created:
--          by - st161569.st161569 (pc029)
--          at - 16:48:37 05/21/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;
LIBRARY RISCV_Processor_lib;
USE RISCV_Processor_lib.types.ALL;

ENTITY dc_ex_pipeline_reg IS
   PORT( 
      alu_mode_dc   : IN     alu_mode_t;
      clk           : IN     std_logic;
      imm_dc        : IN     word_t;
      imm_to_alu_dc : IN     std_logic;
      mem_mode_dc   : IN     mem_mode_t;
      rd_addr_dc    : IN     register_file_t;
      res_n         : IN     std_logic;
      rf_wena_dc    : IN     std_logic;
      rs1_dc        : IN     word_t;
      rs2_dc        : IN     word_t;
      alu_mode_ex   : OUT    alu_mode_t;
      imm_ex        : OUT    word_t;
      imm_to_alu_ex : OUT    std_logic;
      mem_mode_ex   : OUT    mem_mode_t;
      operand_a     : OUT    word_t;
      rd_addr_ex    : OUT    register_file_t;
      rf_wena_ex    : OUT    std_logic;
      rs2_ex        : OUT    word_t
   );

-- Declarations

END dc_ex_pipeline_reg ;

