-- VHDL Entity RISCV_Processor_lib.dc_ex_pipeline_reg.interface
--
-- Created:
--          by - st161569.st161569 (pc043)
--          at - 15:18:21 06/26/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;
LIBRARY RISCV_Processor_lib;
USE RISCV_Processor_lib.types.ALL;
USE RISCV_Processor_lib.isa_defines.ALL;
LIBRARY altera_mf;
USE altera_mf.altera_mf_components.all;

ENTITY dc_ex_pipeline_reg IS
   PORT( 
      alu_mode_dc            : IN     alu_mode_t;
      clk                    : IN     std_logic;
      dbpu_mode_dc           : IN     dbpu_mode_t;
      fwd_rs1_dc             : IN     fwd_select_t;
      fwd_rs2_dc             : IN     fwd_select_t;
      fwd_store_data_dc      : IN     boolean;
      imm_or_bta_dc          : IN     word_t;
      imm_to_alu_dc          : IN     boolean;
      is_conditional_jump_dc : IN     boolean;
      jump_predicted_dc      : IN     boolean;
      mem_mode_dc            : IN     mem_mode_t;
      pc_dc                  : IN     word_t;
      rd_addr_dc             : IN     register_file_t;
      res_n                  : IN     std_logic;
      rs1_dc                 : IN     word_t;
      rs2_dc                 : IN     word_t;
      alu_mode_ex            : OUT    alu_mode_t;
      dbpu_mode_ex           : OUT    dbpu_mode_t;
      fwd_rs1_ex             : OUT    fwd_select_t;
      fwd_rs2_ex             : OUT    fwd_select_t;
      fwd_store_data_ex      : OUT    boolean;
      imm_or_bta_ex          : OUT    word_t;
      imm_to_alu_ex          : OUT    boolean;
      is_conditional_jump_ex : OUT    boolean;
      jump_predicted_ex      : OUT    boolean;
      mem_mode_ex            : OUT    mem_mode_t;
      pc_ex                  : OUT    word_t;
      rd_addr_ex             : OUT    register_file_t;
      rs1_ex                 : OUT    word_t;
      rs2_ex                 : OUT    word_t
   );

-- Declarations

END dc_ex_pipeline_reg ;

