-- VHDL Entity RISCV_Processor_lib.decoder.interface
--
-- Created:
--          by - st161569.st161569 (pc043)
--          at - 14:59:06 05/15/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;
LIBRARY RISCV_Processor_lib;
USE RISCV_Processor_lib.types.ALL;

ENTITY decoder IS
   PORT( 
      instruction_word_dc : IN     word;
      alu_mode_dc         : OUT    alu_mode_t;
      imm_dc              : OUT    word;
      imm_to_alu_dc       : OUT    std_logic;
      rd_addr_dc          : OUT    register_file_t;
      rf_wena_dc          : OUT    std_logic;
      rs1_addr            : OUT    register_file_t;
      rs2_addr            : OUT    register_file_t
   );

-- Declarations

END decoder ;

