-- VHDL Entity RISCV_Processor_lib.divider.interface
--
-- Created:
--          by - st161569.st161569 (pc043)
--          at - 18:17:30 07/09/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;
LIBRARY RISCV_Processor_lib;
USE RISCV_Processor_lib.types.ALL;
USE RISCV_Processor_lib.isa_defines.ALL;
LIBRARY altera_mf;
USE altera_mf.altera_mf_components.all;

ENTITY divider IS
   PORT( 
      clk                : IN     std_logic;
      divider_control_ex : IN     divider_control_t;
      operand_a          : IN     word_t;
      operand_b          : IN     word_t;
      res_n              : IN     std_logic;
      divider_result     : OUT    word_t;
      division_done      : OUT    boolean
   );

-- Declarations

END divider ;

