-- VHDL Entity RISCV_Processor_lib.ex_mem_pipeline_reg.interface
--
-- Created:
--          by - st161569.st161569 (pc029)
--          at - 14:39:49 05/14/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;
LIBRARY RISCV_Processor_lib;
USE RISCV_Processor_lib.types.ALL;

ENTITY ex_mem_pipeline_reg IS
   PORT( 
      alu_result_ex  : IN     word;
      clk            : IN     std_logic;
      rd_addr_ex     : IN     register_file_t;
      res_n          : IN     std_logic;
      alu_result_mem : OUT    word;
      rd_addr_mem    : OUT    register_file_t
   );

-- Declarations

END ex_mem_pipeline_reg ;

