-- VHDL Entity RISCV_Processor_lib.ex_out_mux.interface
--
-- Created:
--          by - st161569.st161569 (pc043)
--          at - 18:34:21 06/12/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;
LIBRARY RISCV_Processor_lib;
USE RISCV_Processor_lib.types.ALL;
USE RISCV_Processor_lib.isa_defines.ALL;
LIBRARY altera_mf;
USE altera_mf.altera_mf_components.all;

ENTITY ex_out_mux IS
   PORT( 
      alu_result_ex  : IN     word_t;
      is_return_addr : IN     boolean;
      return_addr    : IN     word_t;
      ex_out_ex      : OUT    word_t
   );

-- Declarations

END ex_out_mux ;

