-- VHDL Entity RISCV_Processor_lib.if_dc_pipeline_reg.interface
--
-- Created:
--          by - st161569.st161569 (pc043)
--          at - 17:44:33 05/29/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;
LIBRARY RISCV_Processor_lib;
USE RISCV_Processor_lib.types.ALL;

ENTITY if_dc_pipeline_reg IS
   PORT( 
      clk                 : IN     std_logic;
      instruction_word_if : IN     word_t;
      pc_if               : IN     word_t;
      res_n               : IN     std_logic;
      stall_dc            : IN     boolean;
      instruction_word_dc : OUT    word_t;
      pc_dc               : OUT    word_t
   );

-- Declarations

END if_dc_pipeline_reg ;

