-- VHDL Entity RISCV_Processor_lib.io_controller.interface
--
-- Created:
--          by - st161569.st161569 (pc043)
--          at - 17:19:20 07/10/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;
LIBRARY RISCV_Processor_lib;
USE RISCV_Processor_lib.types.ALL;
USE RISCV_Processor_lib.isa_defines.ALL;
LIBRARY altera_mf;
USE altera_mf.altera_mf_components.all;

ENTITY io_controller IS
   PORT( 
      clk            : IN     std_logic;
      io_control     : IN     io_control_t;
      io_rdata       : IN     word_t;
      io_wdata       : IN     word_t;
      res_n          : IN     std_logic;
      io_control_cpu : OUT    io_control_t;
      io_out         : OUT    word_t;
      io_wdata_cpu   : OUT    word_t
   );

-- Declarations

END io_controller ;

