-- VHDL Entity RISCV_Processor_lib.mem_mode_mux.interface
--
-- Created:
--          by - st161569.st161569 (pc043)
--          at - 17:28:40 05/29/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;
LIBRARY RISCV_Processor_lib;
USE RISCV_Processor_lib.types.ALL;

ENTITY mem_mode_mux IS
   PORT( 
      data_memory_result : IN     word_t;
      ex_out_mem         : IN     word_t;
      mem_mode_mem       : IN     mem_mode_t;
      mem_result_mem     : OUT    word_t
   );

-- Declarations

END mem_mode_mux ;

