-- VHDL Entity RISCV_Processor_lib.mem_mode_multiplexer.interface
--
-- Created:
--          by - st161569.st161569 (pc029)
--          at - 16:48:37 05/21/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;
LIBRARY RISCV_Processor_lib;
USE RISCV_Processor_lib.types.ALL;

ENTITY mem_mode_multiplexer IS
   PORT( 
      alu_result_mem     : IN     word_t;
      data_memory_result : IN     word_t;
      mem_mode_mem       : IN     mem_mode_t;
      mem_result_mem     : OUT    word_t
   );

-- Declarations

END mem_mode_multiplexer ;

