-- VHDL Entity RISCV_Processor_lib.mem_wb_pipeline_reg.interface
--
-- Created:
--          by - st161569.st161569 (pc043)
--          at - 18:34:21 06/12/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;
LIBRARY RISCV_Processor_lib;
USE RISCV_Processor_lib.types.ALL;
USE RISCV_Processor_lib.isa_defines.ALL;
LIBRARY altera_mf;
USE altera_mf.altera_mf_components.all;

ENTITY mem_wb_pipeline_reg IS
   PORT( 
      clk            : IN     std_logic;
      mem_result_mem : IN     word_t;
      rd_addr_mem    : IN     register_file_t;
      res_n          : IN     std_logic;
      mem_result_wb  : OUT    word_t;
      rd_addr_wb     : OUT    register_file_t
   );

-- Declarations

END mem_wb_pipeline_reg ;

