-- VHDL Entity RISCV_Processor_lib.mem_wb_pipeline_reg.interface
--
-- Created:
--          by - st161569.st161569 (pc029)
--          at - 16:48:37 05/21/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;
LIBRARY RISCV_Processor_lib;
USE RISCV_Processor_lib.types.ALL;

ENTITY mem_wb_pipeline_reg IS
   PORT( 
      clk            : IN     std_logic;
      mem_result_mem : IN     word_t;
      rd_addr_mem    : IN     register_file_t;
      res_n          : IN     std_logic;
      rf_wena_mem    : IN     std_logic;
      mem_result_wb  : OUT    word_t;
      rd_addr_wb     : OUT    register_file_t;
      rf_wena_wb     : OUT    std_logic
   );

-- Declarations

END mem_wb_pipeline_reg ;

