-- VHDL Entity RISCV_Processor_lib.pc_inc.interface
--
-- Created:
--          by - st161569.st161569 (pc043)
--          at - 15:59:14 05/29/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;
LIBRARY RISCV_Processor_lib;
USE RISCV_Processor_lib.types.ALL;

ENTITY pc_inc IS
   PORT( 
      pc_if : IN     word_t;
      pc_pf : OUT    word_t
   );

-- Declarations

END pc_inc ;

