-- VHDL Entity RISCV_Processor_lib.register_file.interface
--
-- Created:
--          by - st161569.st161569 (pc029)
--          at - 16:48:37 05/21/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;
LIBRARY RISCV_Processor_lib;
USE RISCV_Processor_lib.types.ALL;

ENTITY register_file IS
   PORT( 
      clk           : IN     std_logic;
      mem_result_wb : IN     word_t;
      rd_addr_wb    : IN     register_file_t;
      res_n         : IN     std_logic;
      rf_wena_wb    : IN     std_logic;
      rs1_addr      : IN     register_file_t;
      rs2_addr      : IN     register_file_t;
      rs1_dc        : OUT    word_t;
      rs2_dc        : OUT    word_t
   );

-- Declarations

END register_file ;

