-- VHDL Entity RISCV_Processor_lib.res_synchronizer.interface
--
-- Created:
--          by - st161569.st161569 (pc043)
--          at - 17:56:22 07/11/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;
LIBRARY RISCV_Processor_lib;
USE RISCV_Processor_lib.types.ALL;

ENTITY res_synchronizer IS
   PORT( 
      clk     : IN     std_logic;
      res_key : IN     std_logic;
      res_n   : OUT    std_logic
   );

-- Declarations

END res_synchronizer ;

