-- VHDL Entity RISCV_Processor_lib.rom.interface
--
-- Created:
--          by - st161569.st161569 (pc029)
--          at - 16:19:42 05/14/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;
LIBRARY RISCV_Processor_lib;
USE RISCV_Processor_lib.types.ALL;

ENTITY rom IS
   PORT( 
      clk                 : IN     std_logic;
      pc_if               : IN     std_logic_vector (7 DOWNTO 0);
      res_n               : IN     std_logic;
      instruction_word_if : OUT    word
   );

-- Declarations

END rom ;

