-- VHDL Entity RISCV_Processor_lib.rs1_fwd_mux.interface
--
-- Created:
--          by - st161569.st161569 (pc043)
--          at - 12:51:01 05/22/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;
LIBRARY RISCV_Processor_lib;
USE RISCV_Processor_lib.types.ALL;

ENTITY rs1_fwd_mux IS
   PORT( 
      alu_result_mem : IN     word_t;
      fwd_rs1_ex     : IN     fwd_select_t;
      mem_result_wb  : IN     word_t;
      rs1_ex         : IN     word_t;
      operand_a      : OUT    word_t
   );

-- Declarations

END rs1_fwd_mux ;

