-- VHDL Entity RISCV_Processor_lib.rs2_multiplexer.interface
--
-- Created:
--          by - st161569.st161569 (pc029)
--          at - 16:48:37 05/21/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;
LIBRARY RISCV_Processor_lib;
USE RISCV_Processor_lib.types.ALL;

ENTITY rs2_multiplexer IS
   PORT( 
      imm_ex        : IN     word_t;
      imm_to_alu_ex : IN     std_logic;
      rs2_ex        : IN     word_t;
      operand_b     : OUT    word_t
   );

-- Declarations

END rs2_multiplexer ;

