-- VHDL Entity RISCV_Processor_lib.store_data_fwd_mux.interface
--
-- Created:
--          by - st161569.st161569 (pc043)
--          at - 12:59:22 05/22/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;
LIBRARY RISCV_Processor_lib;
USE RISCV_Processor_lib.types.ALL;

ENTITY store_data_fwd_mux IS
   PORT( 
      fwd_store_data_mem : IN     std_logic;
      mem_result_wb      : IN     word_t;
      rs2_mem            : IN     word_t;
      store_data         : OUT    word_t
   );

-- Declarations

END store_data_fwd_mux ;

