--
-- VHDL Architecture RISCV_Processor_lib.top_tb.struct
--
-- Created:
--          by - st161569.st161569 (pc043)
--          at - 17:11:54 06/26/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;
LIBRARY RISCV_Processor_lib;
USE RISCV_Processor_lib.types.ALL;


ARCHITECTURE struct OF top_tb IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL alu_result_ex : word_t;
   SIGNAL clk           : std_logic;
   SIGNAL pc            : word_t;
   SIGNAL res_n         : std_logic;


   -- Component Declarations
   COMPONENT clk_res_gen
   PORT (
      clk   : OUT    std_logic ;
      res_n : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT cpu
   PORT (
      clk           : IN     std_logic ;
      res_n         : IN     std_logic ;
      alu_result_ex : OUT    word_t ;
      pc            : OUT    word_t 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : clk_res_gen USE ENTITY RISCV_Processor_lib.clk_res_gen;
   FOR ALL : cpu USE ENTITY RISCV_Processor_lib.cpu;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   clk_res_gen_i : clk_res_gen
      PORT MAP (
         clk   => clk,
         res_n => res_n
      );
   cpu_i : cpu
      PORT MAP (
         clk           => clk,
         res_n         => res_n,
         alu_result_ex => alu_result_ex,
         pc            => pc
      );

END struct;
