--
-- VHDL Architecture UPN_Rechner_Lib.upn_tb.struct
--
-- Created:
--          by - st161569.st161569 (pc043)
--          at - 17:32:34 04/24/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

LIBRARY UPN_Rechner_Lib;

ARCHITECTURE struct OF upn_tb IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL clk   : std_logic;
   SIGNAL res_n : std_logic;
   SIGNAL tx_n  : std_logic;


   -- Component Declarations
   COMPONENT clk_res_gen
   PORT (
      clk   : OUT    std_logic ;
      res_n : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT tester
   PORT (
      tx_n : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT upn
   PORT (
      clk   : IN     std_logic ;
      res_n : IN     std_logic ;
      tx_n  : IN     std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : clk_res_gen USE ENTITY UPN_Rechner_Lib.clk_res_gen;
   FOR ALL : tester USE ENTITY UPN_Rechner_Lib.tester;
   FOR ALL : upn USE ENTITY UPN_Rechner_Lib.upn;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   clk_res_gen_i : clk_res_gen
      PORT MAP (
         clk   => clk,
         res_n => res_n
      );
   tester_i : tester
      PORT MAP (
         tx_n => tx_n
      );
   upn_i : upn
      PORT MAP (
         clk   => clk,
         res_n => res_n,
         tx_n  => tx_n
      );

END struct;
