-- VHDL Entity UPN_Rechner_Lib.upn_tb.symbol
--
-- Created:
--          by - st161569.st161569 (pc043)
--          at - 15:57:51 04/24/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

ENTITY upn_tb IS
-- Declarations

END upn_tb ;

