--
-- VHDL Architecture UPN_Rechner_Lib.upn.struct
--
-- Created:
--          by - st161569.st161569 (pc043)
--          at - 17:32:28 04/24/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

LIBRARY UPN_Rechner_Lib;

ARCHITECTURE struct OF upn IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL key : std_logic;


   -- Component Declarations
   COMPONENT button
   PORT (
      clk   : IN     std_logic ;
      res_n : IN     std_logic ;
      tx_n  : IN     std_logic ;
      key   : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : button USE ENTITY UPN_Rechner_Lib.button;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_0 : button
      PORT MAP (
         clk   => clk,
         res_n => res_n,
         tx_n  => tx_n,
         key   => key
      );

END struct;
